### ISSUE TITLE
Failing static_pages request spec

### ISSUE THREAD

**Issue by akurilin** [sionc/sager_app#1]
[alex@arch_lianli sager_app]$ bundle exec guard
Guard uses NotifySend to send notifications.
Guard is now watching at '/home/alex/code/sager_app'
Guard::RSpec is running, with RSpec 2!
Running all specs
....................................................F..

Failures:

  1) StaticPages Home page should have the content 'Home'
     Failure/Error: page.should have_content('Home')
       expected there to be content "Home" in "Sager\n    \n          Sager\n\n    Overview\n  \n  \n    About Us\n  \n\n      \n      \n        \n        \n  \n    \n    \n  \n  \n    \n      \n    \n  \n\n\n         \n     \n  "
     # ./spec/requests/static_pages_spec.rb:9:in `block (3 levels) in <top (required)>'

Finished in 1.48 seconds
55 examples, 1 failure

Failed examples:

rspec ./spec/requests/static_pages_spec.rb:7 # StaticPages Home page should have the content 'Home'
Coverage report generated for RSpec to /home/alex/code/sager_app/coverage. 107 / 107 LOC (100.0%) covered.

**Comment by sionc** [comment]
Deleted request spec for home because it is no longer valid

Fixed in f8a066468506cc4fe8b6b5b4e486e1824cac917c
