### ISSUE TITLE
2 sensor_spec.rb model test cases take too long

### ISSUE THREAD

**Issue by akurilin** [sionc/sager_app#4]
The top two test cases below take a really long time to execute. Let's try to keep everything really snappy, and just do enough functionality validation to allow us to sleep well at night. Let's try to keep it under 100msec, if possible.

~/code/sager_app/spec/models (develop)$ rspec sensor_spec.rb -p
.........

Top 9 slowest examples:
  Sensor should calculate kwh usage for the week upto the given date
    **7.52 seconds ./sensor_spec.rb:89**
  Sensor should calculate kwh usage for a given date
    **1.02 seconds ./sensor_spec.rb:66**
  Sensor should calculate kwh usage for one hour for a given date and hour
    0.24685 seconds ./sensor_spec.rb:47
  Sensor should not have an empty or nil name
    0.2077 seconds ./sensor_spec.rb:4
  Sensor should be able to have same local id across hubs
    0.03111 seconds ./sensor_spec.rb:30
  Sensor should be able to have duplicate names for different hubs
    0.03047 seconds ./sensor_spec.rb:17
  Sensor should not have a duplicate name for the same hub
    0.0226 seconds ./sensor_spec.rb:10
  Sensor should not have same local id for one hub
    0.01976 seconds ./sensor_spec.rb:39
  Sensor should not exist without an associated hub
    0.00708 seconds ./sensor_spec.rb:24

**Comment by sionc** [comment]
I have reduced the number of data points used for the test. It takes ~2 secs now to run all the tests.

See 9224f3d5b4596afca492be6186dd80cf15461bad

**Comment by akurilin** [comment]
Awesome job, thanks for taking care of this!
